### ISSUE TITLE
ram大小疑似错误？

### ISSUE THREAD

**Issue by yunline** [IOsetting/hk32f030m-template#12]
代码中，ram的大小是4k bytes
https://github.com/IOsetting/hk32f030m-template/blob/fb51f2176255042ec50b8f48c79d5b3d0719f096/Libraries/LDScripts/hk32f030mf4p6.ld#L30-L35

然而根据手册，sram的大小是2k bytes
![图片](https://github.com/IOsetting/hk32f030m-template/assets/31395137/1e207466-d364-40e2-aead-9bc033b9f035)

是错误吗？

**Comment by IOsetting** [comment]
手册2KB, 实测4KB, 已经被多次验证.
http://nerdralph.blogspot.com/2021/01/trying-to-test-ten-cent-tiny-arm-m0-mcu.html
https://www.eevblog.com/forum/microcontrollers/$0-25-hk32f030m-(cortex-m0-32mhz-16kb-2kb)/

**Comment by yunline** [comment]
感谢大佬的回答。
感谢大自然馈赠的内存。
